# Generated by Django 4.1.4 on 2023-05-16 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_foodname_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodname',
            name='updated_at',
        ),
    ]
